views.py
from flask import current_app, Blueprint, request, session, g, redirect, url_for, abort, render_template, flash
import datetime, os
from werkzeug.utils import secure_filename
main_app = Blueprint('main_app', __name__, template_folder='templates')

@main_app.route('/')
def index(name=None):
    #print(current_app.config.get('HOST'))
    return render_template('index.html')
    
@main_app.route('/education')
def education():
    return render_template('education.html')
    
@main_app.route('/burials')
def burials():
    return render_template('burials.html')

@main_app.route('/donate')
def donate():
    return render_template('donate.html')

@main_app.route('/about')
def about():
    return render_template('about.html')

def allowed_file(filename):
    return '.' in filename and \
        filename.rsplit('.', 1)[1] == 'pdf'

# Route that will process the file upload
@main_app.route('/upload', methods=['POST'])
def upload():
    # Get the name of the uploaded file
    file = request.files['file']
    # Check if the file is one of the allowed types/extensions
    if file and allowed_file(file.filename):
        # Make the filename safe, remove unsupported chars
        filename = secure_filename(file.filename)
        # Move the file form the temporal folder to
        # the upload folder we setup
        file.save(os.path.join('/timetables', filename))
        # Redirect the user to the uploaded_file route, which
        # will basicaly show on the browser the uploaded file
        return index()
        # redirect(url_for('main_app.index') )

@main_app.route('/admin/timetable_upload')
def timetable_upload():
    return render_template('timetable_upload.html')
    
    

templates/about.html
{% extends "base.html" %}
{% block title %}About{% endblock %}
{% block head %}
  {{ super() }}
  <style type="text/css" media="all">
      p.flow-text {
          font-size: 16px;
          font-weight: bold;
      }
  </style>
{% endblock %}

{% block header %}
    {{ super() }}
{% endblock %}

{% block content %}
     
<div class="container">
    <h5><b>About</b></h5>
    <p class="flow-text">Madrassatul Noor was actually the main reason and source for the establishment of the East African 
        community at the St Matthews estate in Leicester. The community has now been serving the whole 
        area of the city. <br><br>The Madrasah, formed almost two decades ago, has passed a number of phases and 
        encountered numerous hurdles. Members of the East African community, who were dispersed to 
        Leicester in 1990s, discussed the importance of bringing together children and young people so that 
        they could obtain faith education. Sincere efforts were then made, and with the help of the Almighty 
        the Madrasah was formed in the second half of the 1990’s decade.
    </p>
    <br><br><br><br>
    
    <p class="flow-text">
        To know more about the development of this website, please <a class="modal-trigger" href="#about-modal">click here</a>.
        Alternatively, you can get in touch with the developer of this website <a href="https://distilled.me/anees" target="_blank">here</a>.
    </p>
      <!-- Modal Structure -->
      <div id="about-modal" class="modal">
        <div class="modal-content" style="font-size: 16px; font-weight: bold; color: black;">
          <h5><b>About this site</b></h5>
          <p style="line-height: 2em;">This website is a community-driven project that began in early 2016.
          If you would like to know more or get in touch with the developer of this website, please <a href="https://distilled.me/anees" target="_blank">click here.</a><br><br>
          This project was made possible with the help of open source frameworks like <a href="http://flask.pocoo.org/" target="_blank">Flask</a> and <a href="http://materializecss.com/" target="_blank">Materialize</a>.<br>
          The developer of this website and Madrassatul Noor do not own any of the images used in this website. The symbol images are <a href="http://www.freepik.com/" target="_blank">designed by Freepik</a>
          and the image of the mosque used in the home page was obtained <a href="http://www.markazislam.com/beautiful-mosques/" target="_blank">from here</a>.
          </p>
        </div>
        <div class="modal-footer">
          <a href="#!" class="modal-action modal-close waves-effect waves-green btn-flat"><b>Close</b></a>
        </div>
      </div>  
    <!--
    var mapProp = {
        center:new google.maps.LatLng(52.6412901,-1.1304800),
        zoom:18,
        mapTypeId:google.maps.MapTypeId.ROADMAP
    };
    -->

</div>
{% endblock %}

<script type="text/javascript">

    $(document).ready( function() {
        $('.modal-trigger').leanModal();
    });
</script>

{% block footer %}
    {{ super() }}
{% endblock %}

templates/base.html
<!DOCTYPE html>
<head>
{% block head %}
<title>Madrassatul Noor - {% block title %}{% endblock %}</title>
<meta name="google-site-verification" content="L5B9RrkZxt4Hr_qYfvJohW1sgFHFLwvhVBFYYJEeGd0" />
<meta name="msvalidate.01" content="66A81C00FBE6A8BB5260E602A9C216AC" />

<link rel="stylesheet" type="text/css" href="{{ url_for('bower.static', filename='Materialize/dist/css/materialize.css') }}"/>
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<link rel="shortcut icon" href="{{ url_for('static', filename='images/favicon.ico') }}">
<link href='https://fonts.googleapis.com/css?family=Josefin+Slab' rel='stylesheet' type='text/css'>
<link href='https://fonts.googleapis.com/css?family=Cookie' rel='stylesheet' type='text/css'>

<script src="{{ url_for('bower.static', filename='jquery/dist/jquery.min.js') }}"></script>
<script src="{{ url_for('bower.static', filename='Materialize/dist/js/materialize.min.js') }}"></script>

<style type="text/css" media="all">
    html {
        font-family : 'Josefin Slab';
    }
    
    ul#nav-mobile span {
        top: 15px;
        position:relative;
    }
    
    i.material-icons {
        font-size: 0.90em;
        padding-right: 8px;
    }
</style>

{% endblock %}

</head>

<body>

{% block header %}
<div class="navbar-fixed">
<nav class="blue-grey darken-3">
<div class="nav-wrapper" style="padding: 0 5%;">
  <a href="#" class="brand-logo" style="top: 10%">
    <img style="max-height: 45px; width: 12%; left: 4%; position: relative;" src="{{ url_for('static', filename='images/minaret.png') }}"/>
    Madrassatul Noor
  </a>
  <ul id="nav-mobile" class="right">
    <li><a href="{{url_for('main_app.index')}}"><span>Home</span></a></li>
    <li><a href="{{url_for('main_app.education')}}"><span>Education</span></a></li>
    <li><a href="{{url_for('main_app.burials')}}"><span>Burials</span></a></li>
    <li><a href="{{url_for('main_app.donate')}}"><span>Donate</span></a></li>
    <li><a href="{{url_for('main_app.about')}}"><span>About</span></a></li>
  </ul>
</div>
</nav>
</div>

{% endblock %}

{% block content %}{% endblock %}

{% block footer %}
<footer class="page-footer grey darken-4">
  <div class="container">
    <div itemscope itemtype="http://schema.org/Organization" class="row">
      <div class="col l7 s12">
        <!--<h5 class="white-text">Footer Content</h5>-->
        <p class="grey-text text-lighten-4">
            <span itemprop="name">Madrassatul Noor</span> is a registered charity based in Leicester, UK (Charity number: 1146906).
            <span itemprop="name" style="display: none;">Masjid An Noor</span>
        </p>
      </div>
      <div class="col l4 offset-l1 s12">
        <h5 class="white-text">Contact Us</h5>
        <ul>
          <li class="grey-text text-lighten-3">
                <i class="material-icons">location_on</i>
                <span itemprop="address" itemscope itemtype="http://schema.org/PostalAddress">
                    <span itemprop="streetAddress">170a Belgrave Gate</span>,<span itemprop="addressRegion">Leicester</span>, <span itemprop="postalCode">LE1 3XL</span>
                </span>    
            </li>
          <li class="grey-text text-lighten-3">
                <i class="material-icons">phone</i>
                <span itemprop="telephone">0116 251 9952</span>
          </li>
          <li class="grey-text text-lighten-3">
                <i class="material-icons" style="position: relative; top: 2px;">email</i>
                <a href="mailto:madrasatulnoor.01@gmail.com"><span itemprop="email">madrasatulnoor.01@gmail.com</span></a>
          </li>
        </ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container">
    © 2016 Copyright
    <a class="modal-trigger grey-text text-lighten-4 right" href="#about-modal">About this site</a>
          <!-- Modal Structure -->
          <div id="about-modal" class="modal">
            <div class="modal-content" style="font-size: 16px; font-weight: bold; color: black;">
              <h5><b>About this site</b></h5>
              <p style="line-height: 2em;">This website is a community-driven project that began in early 2016.
              If you would like to know more or get in touch with the developer of this website, please <a href="http://smarturl.it/anees-m?IQid=noor" target="_blank">click here.</a><br><br>
              This project was made possible with the help of open source frameworks like <a href="http://flask.pocoo.org/" target="_blank">Flask</a> and <a href="http://materializecss.com/" target="_blank">Materialize</a>.<br>
              The developer of this website and Madrassatul Noor do not own any of the images used in this website. The symbol images are <a href="http://www.freepik.com/" target="_blank">designed by Freepik</a>
              and the image of the mosque used in the home page was obtained <a href="http://www.markazislam.com/beautiful-mosques/" target="_blank">from here</a>.
              </p>
            </div>
            <div class="modal-footer">
              <a href="#!" class="modal-action modal-close waves-effect waves-green btn-flat"><b>Close</b></a>
            </div>
          </div>  
    </div>
  </div>
</footer>

{% endblock %}

<script type="text/javascript">

    $(document).ready( function() {
        $('.modal-trigger').leanModal();
    });
</script>
</body>

templates/burials.html
{% extends "base.html" %}
{% block title %}Burials{% endblock %}
{% block head %}
  {{ super() }}
  <style type="text/css" media="all">
      p.flow-text {
          font-size: 16px;
          font-weight: bold;
      }
  </style>
{% endblock %}

{% block header %}
    {{ super() }}
{% endblock %}


{% block content %}
     
<div class="container">
    <h5><b>Burials</b></h5>
    <p class="flow-text">The community of Madrassatul Noor Leicester has been working as a Funeral Arranger, with
        the collaboration and assistance of the Muslim Burial Council of Leicestershire (MBCOL). 
        This means that this community has been authorised to represent its members in the 
        preparation of the burial process, from when the death occurs until the burial takes place. 
        By law, individual families are not authorised to arrange funerals of their beloved ones when 
        they pass away. <br><br>
        The aim of the Burial fund is to support Muslims (individuals and families) who are residing in UK for their
        funeral and burial expenses when they will face the death of a loved one.
        Whenever a death occurs, the organisation’s Burial Committee need to be contacted as 
        soon as possible and they will InshaaAllah offer the support needed and they will contact 
        relevant authorities until the process is complete.
        <br><br>
        The membership to the Madrassatul Noor Burial Fund is open to every Muslim male or female resident 
        of UK with the age of 18 and above. 
        To be eligible for the full support of the funeral, every member should be active 
        by contributing the agreed amount of money every month on time without missing a payment.
        <br><br>
        Please contact the Organisation if you need more information regarding this service.
    </p>
    
</div>

{% endblock %}

{% block footer %}
    {{ super() }}
{% endblock %}

templates/donate.html
{% extends "base.html" %}
{% block title %}About{% endblock %}
{% block head %}
  {{ super() }}
  <style type="text/css" media="all">
      p.flow-text {
          font-size: 16px;
          font-weight: bold;
      }
  </style>
{% endblock %}

{% block header %}
    {{ super() }}
{% endblock %}

{% block content %}
     
<div class="container">
    <h5><b>Donate</b></h5>
    <p class="flow-text">If you would like to make a donation, please use the following details or contact us if you need
    further assistance. JazakAllah Khayr!</p>
    <div class="row">
    <div id="donate-card" class="col s7">
        <div class="card blue-grey darken-1">
            <div class="card-content white-text">
                <span class="card-title">Madrassatul Noor Leicester</span>
                    <p style="font-size: medium;">
                    <table style="line-height: 0em;">
                        <tr>
                            <td>Bank: </td><td>Lloyds TSB, Town Hall Square, Leicester</td>
                        </tr>
                        <tr>
                            <td>Account No: </td><td>45127768</td>
                        </tr>
                        <tr>
                            <td>Sort Code: </td><td>30-94-97</td>
                        </tr>
                        <tr>
                            <td>International Bank a/c: </td><td>LOYDGB21029 GB27LOYD30949745127768</td>
                        </tr>
                    </table>
                    </p>
            </div>
        </div>
    </div>
    </div>
    <p class="flow-text">
        If you have a PayPal account, then you can also donate by clicking on the link below
        <!-- PayPal Logo -->
        <table border="0" cellpadding="10" cellspacing="0" align="center">
            <tr>
                <td align="center"><a href="https://www.paypal.me/madrassatulnoor" title="Pay with PayPal" onclick="javascript:window.open('https://www.paypal.me/madrassatulnoor','WIPaypal','toolbar=no, location=no, directories=no, status=no, menubar=no, scrollbars=yes, resizable=yes, width=1060, height=700'); return false;"><img src="https://www.paypalobjects.com/webstatic/mktg/Logo/pp-logo-150px.png" border="0" alt="PayPal Logo"></a></td>
            </tr>
        </table><!-- PayPal Logo -->
    </p>

</div>
{% endblock %}

{% block footer %}
    {{ super() }}
{% endblock %}

templates/education.html
{% extends "base.html" %}
{% block title %}Services{% endblock %}
{% block head %}
  {{ super() }}
  <style type="text/css" media="all">
      p.flow-text {
          font-size: 16px;
          font-weight: bold;
      }

      ul#madrassah-list > li {
          list-style-type: circle;
          display: list-item;
          font-weight: bold;
      }
  </style>
{% endblock %}

{% block header %}
    {{ super() }}
{% endblock %}


{% block content %}
     
<div class="container">
    <h5><b>Madrassah</b></h5>
    <p class="flow-text">
    The Madrassah is based in the An Noor Mosque at Belgrave Gate, working hand in hand with the 
    An Noor community. <br>  
    Currently 130 students attend the Madrassah.
    </p>
    
    <ul id="madrassah-list" style="padding-left:25px;">
        <li>The students must be 4 years and older in order to enrol.</li>
        <li>The Madrassah runs from 17:00 – 19:00 Monday to Thursday.</li>
        <li>The students are required to dress up appropriately when attending.</li>
        <li>There are five classes, and boys and girls are taught separately.</li>
        <li>The subjects taught at the Madrassah are reciting and memorising the holy Quran, Fiq-h, Arabic, 
     Islamic manners based on the Quranic verses, Islamic Monotheism, Etiquettes, Islamic History 
     and the Prophet’s PBUH lifestyle.</li>
    </ul>

    <p class="flow-text">The main objective of the Madrassah has been to help the students develop their skills and the 
        understanding of the Deen, and at the same time encourage them to live their entire life according 
        to the teachings of the Prophet. In that way, it is expected that they will InshaaAllah be able to fit in 
        the wider community.<br><br>
        Madrassatul Noor has five female teachers and four males, and every single one works as a 
        volunteer. Almost every teacher is qualified. The Madrassah has enough First Aiders, and has 
        developed a number of policies, such as the Child Protection, the Anti-Bullying and the Health and 
        Safety policies.<br><br>
        To download the pupil admission form, please <a target="_blank" href="{{ url_for('static', filename='noor_admission_form.pdf') }}">click here</a>.
    </p>
</div>

{% endblock %}

{% block footer %}
    {{ super() }}
{% endblock %}

templates/index.html
{% extends "base.html" %}
{% block title %}Leicester{% endblock %}
{% block head %}
  {{ super() }}
<style type="text/css" media="all">

    .custom-symbol {
        width:30%; 
        margin-left:33%; 
        margin-top: 10%;
    }
    
</style>
{% endblock %}

{% block header %}
    {{ super() }}
{% endblock %}


{% block content %}

<div style="font-size:95%; text-align:center; font-weight:bold; line-height:0px;">
    <img style="width:30%;" src="{{ url_for('static', filename='images/bismillah_bw.jpg') }}"/>
    <p>In the name of God, the most gracious, the most merciful.</p>
</div>
<img style="width:100%" src="{{ url_for('static', filename='images/beautiful_mosque.jpg') }}"/>

<div class="row" style="text-align: center;">
      <div class="col s12">
        <span class="flow-text" style="font-family:'Cookie'; font-size: 40px;">Started in 1997, The An-Noor establishment is a...</span></div>
</div>

<div class="row container">
  <div id="masjid-card" class="card-panel col s3 offset-s1">
      <img class="custom-symbol" src="{{ url_for('static', filename='images/masjid.png') }}"/>
      <p style="left:39%; position: relative; font-weight: 700;">Masjid</p>
  </div>
  <div id="madrasah-card" class="card-panel col s3 offset-s1">
      <img class="custom-symbol" src="{{ url_for('static', filename='images/madrasah.png') }}"/>
      <p style="left:34%; position: relative; font-weight: 700;">Madrasah</p>
  </div>
  <div id="people-card" class="card-panel col s3 offset-s1">
      <img class="custom-symbol" src="{{ url_for('static', filename='images/community.png') }}"/>
      <p style="left:23%; position: relative; font-weight: 700;">Community Centre</p>      
  </div>
</div>

<div class="row blue-grey lighten-5">
    
  <div class="col s3 offset-s3" style="font-size: 23px; font-weight: bold; padding-top: 30px;">
        Download prayer timetable:
  </div>
  <div class="col s3">
    <a target="_blank" id="current-timetable">
      <img style="width: 28%; padding-top: 10%; padding-left: 4%;" src="{{ url_for('static', filename='images/calendar.png') }}"/>
      <p id="current-month" style="margin-left: 4%; font-weight: 700;">January 2016</p>
    </a>
  </div>
</div>

<script type="text/javascript">

    $(document).ready( function() {
        
        var date_object = new Date();
        
        // first we show the month in the placeholder
        var month_list = [ "January", "February", "March", "April", "May", "June", 
               "July", "August", "September", "October", "November", "December" ];

        $("#current-month").html(month_list[date_object.getMonth()] + " " + date_object.getUTCFullYear())

        var month = date_object.toDateString().split(' ')[1].toLowerCase();
        var year = date_object.toDateString().split(' ')[3];

        var current_timetable = "timetable_" + month + "_" + year + ".pdf";

        var current_file_path = "{{ url_for('static', filename='timetables/') }}" + current_timetable;

        // set filename for current month
        $("#current-timetable").attr( 
            "href", current_file_path
        );
    });
    
    $(".custom-symbol").hover(function() {
        $(this).parent().addClass("z-depth-2"); 
    });
    
    $(".custom-symbol").mouseout(function() {
        $(this).parent().removeClass("z-depth-2");
    });
    
     $("#masjid-card, #madrasah-card, #people-card").hover(function() {
        $(this).addClass("z-depth-2") 
    });
    
    $("#masjid-card, #madrasah-card, #people-card").mouseout(function() {
        $(this).removeClass("z-depth-2") 
    });
    
</script>

{% endblock %}

{% block footer %}
    {{ super() }}
{% endblock %}

templates/timetable_upload.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Upload timetable</title>
  </head>
  <body>
    <div class="container">
      <div class="header">
        <h3 class="text-muted">Please select your timetable:</h3>
            <p>Note that your file must be of the following format<i>timetable_mmm_yyyy.pdf</i>
                <br>
                For example: timetable_feb_2016.pdf
            </p>
      </div>
      <hr/>
      <div>
      
      <form action="/upload" method="post" enctype="multipart/form-data">
        <input type="file" name="file"><br /><br />
        <input type="submit" value="Upload">
      </form>
      </div>
    </div>
  </body>
</html>